FROM php:8.2-cli
WORKDIR /app
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    curl \
    libzip-dev \
    && docker-php-ext-install zip
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
COPY . .

RUN composer install

CMD php artisan serve --host=0.0.0.0 --port=8000